config/routes.rb
Rails.application.routes.draw do

  resources :trainings
  get 'users/show'

  get 'users/index'

  get 'home/show'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'welcome/index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'forms_questions/submit', to: 'forms_questions#submit'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :answers
  resources :forms_questions
  resources :forms
  resources :questions
  resources :recommendations
  resources :recommended_list
  # resources :users, only: [:show, :index]
  get 'profile', to: 'profiles#index'
  get 'profile/edit', to: 'profiles#edit'
  patch 'profile/update', to: 'profiles#update'
  post 'tranings/invite/', to: 'trainings#invite'
  post 'tranings/reject/', to: 'trainings#reject'
  post 'tranings/accept/', to: 'trainings#accept'
  post 'tranings/deny/', to: 'trainings#deny'
  post 'users/set_admin/', to: 'users#set_admin'
  post 'users/unset_admin/', to: 'users#unset_admin'
  get 'users/:user_id' => 'users#show', as: :usersshow
  root to: "home#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/training.rb
class Training < ApplicationRecord
    #has_one :questions
    #has_one :forms
    validates :title, presence: :true
    validates :title, length: {maximum: 100}
    has_many :training_logs, :class_name => 'TrainingLog'
    has_many :users, through: :training_logs
    belongs_to :form #, optional: true
    belongs_to :question #, optional: true

    #instance methods
    def set_form(form_id) #sets the associated form
        self.form_id = form_id
    end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController

  before_action :authorize_admin, only: [:show, :new, :edit, :update, :destroy]

  # GET /trainings
  # GET /trainings.json
  def index
    @trainings = Training.all
    @questions = Question.all
    @forms = Form.all
    @trainingLogs = TrainingLog.all
    @invited = @trainingLogs.where(recommendation: "Invited", user_id: current_user.id);
    @date_after = Date.today..Date.today+50.year
    @going = TrainingLog.joins(:training).where(user_id: current_user.id, recommendation: "Going", trainings: {date: @date_after})
  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
    @training = Training.find(params[:id])
    @questions = Question.all
    @forms = Form.all
    @trainingLogs = TrainingLog.all
    @invites = @trainingLogs.where(training_id: @training.id);
    @recom = @trainingLogs.where(training_id: @training.id, recommendation: "Recommended");  #filters like !recommended or going to be added later
  end

  # GET /trainings/new
  def new
    @training = Training.new
    @questions = Question.all
    @forms = Form.all
  end

  def invite
    @traininglog = TrainingLog.find(params[:id])
    @traininglog.recommendation = "Invited"
    @traininglog.save
    redirect_back(fallback_location: root_path)
  end

  def reject
    @traininglog = TrainingLog.find(params[:id])
    @traininglog.recommendation = "Rejected"
    @traininglog.save
    redirect_back(fallback_location: root_path)
  end

  def accept
    @traininglog = TrainingLog.find(params[:id])
    @traininglog.recommendation = "Going"
    @traininglog.save
    redirect_back(fallback_location: root_path)
  end

  def deny
    @traininglog = TrainingLog.find(params[:id])
    @traininglog.recommendation = "Not Going"
    @traininglog.save
    redirect_back(fallback_location: root_path)
  end

  # GET /trainings/1/edit
  def edit
    @training = Training.find(params[:id])
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = Training.new(training_params)
    respond_to do |format|
      if @training.save
        @trainingref = @training.form
        @trainingref.training_id = @training.id
        @trainingref.save

        format.html { redirect_to trainings_path, notice: 'Training was successfully created.' }
        format.json { render :show, status: :created, location: @training }
      else
        format.html { render :new }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1
  # PATCH/PUT /trainings/1.json
  def update
    @training = Training.find(params[:id])
    respond_to do |format|
      if @training.update(training_params)
        @trainingref = @training.form
        @trainingref.training_id = @training.id
        @trainingref.save
        format.html { redirect_to @training, notice: 'Training was successfully updated.' }
        format.json { render :show, status: :ok, location: @training }
      else
        puts @training.errors.full_messages
        format.html { render :edit }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training = Training.find(params[:id])
    @training.destroy
    respond_to do |format|
      format.html { redirect_to trainings_url, notice: 'Training was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def training_params
      params.require(:training).permit(:assoc_skill, :description, :title, :venue, :date, :question_id, :form_id)
    end

  def authorize_admin
    if !current_user.is_admin?
      flash[:error_header] = "Sorry, you are not authorized to view this page."
      flash[:error_body] = "You have been redirected to your profile."
      redirect_to '/profile'
    end
  end

end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.erb
<div class="ui segments">
    <div class="ui horizontal segments">
      <div class="ui segment">
    <h3 class="ui dividing header"><i class="red info circle icon"></i>Training Information</h3>

    <%= form_for(training) do |f| %>

    <div class="ui form">

    <div class="field">
    <label>Title</label>
    <%= f.text_field :title %>
    <% if @training.errors[:title].any? %>
    <div class="ui basic red pointing prompt label transition visible">
    <%= "Title " << @training.errors[:title].join(", ") %>
    </div>
    <% end %>
    <br>
    </div>

    <div class="field">
    <label>Description</label>
    <%= f.text_field :description %>
    <br>
    </div>
    <div class="field">
    <label>Venue</label>
    <%= f.text_field :venue %>
    <br>
    <div class="field">
    <label>Date</label>
    <%= f.date_field :date, :placeholder => "mm-dd-yyyy" %>
    <br>
    </div>
    </div>
    </div>
    </div> <!-- end info segment -->
    <div class="ui segment" style="width: 30%">
        <h3 class="ui dividing header"><i class="red help circle icon"></i> Choose Associated Skill and Form </h3>
        <div class="field">
        <label><b>Question</b></label><br>
        <%= f.collection_select(:question_id, Question.all, :id, :questionDescription) %><br>
        <% if @training.errors[:question].any? %>
        <div class="ui basic red pointing prompt label transition visible">
        <%= "Question " << @training.errors[:question].join(", ") %>
        </div>
        <% end %>
        </div><br>
        <div class="field">
        <label><b>Form</b></label><br>
        <%= f.collection_select(:form_id, Form.all, :id, :title)  %><br>
        <% if @training.errors[:form].any? %>
        <div class="ui basic red pointing prompt label transition visible">
        <%= "Form " << @training.errors[:form].join(", ") %>
        </div>
        <% end %>
        </div>
    </div>
  </div>
  <div class="ui center aligned segment">
  <div class="eight wide centered column">
  Please review all fields before submitting.
  <br><br>
  <button type="submit" name="submit-button" class="ui red button submit-button" id = "red_button">
    Save
  </button>
  <%= link_to 'Cancel', trainings_path, class:"ui black button"%>
  </div>
  <% end %>
  </div>
  </div>

<!-- <%= form_for(training) do |f| %>
  <% if training.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(training.errors.count, "error") %> prohibited this training from being saved:</h2>

      <ul>
      <% training.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %> -->

  <!-- <div class="actions">
    <%= f.submit %>
  </div>
<% end %> -->

app/views/trainings/edit.html.erb
<%= render :file=> 'app/views/partials/sidebar.html.erb' %>

<div class = "pusher">
  <div class="ui basic segment">
    <div class="left">
      <h1 class="ui header"><i class="red edit icon"></i>Edit Training: <%= @training.title %></h1>
    </div>
    
  </div>
  <div class="clear"></div>
    <%= render 'form', training: @training %>
  </div>

app/views/trainings/index.html.erb
<%= render :file=> 'app/views/partials/sidebar.html.erb' %>

<div class = "pusher">
  <div class="ui basic segment">
    <div class="left">
      <h1 class="ui header"><i class="red block layout icon"></i>Trainings</h1>
    </div>
    <% if current_user.is_admin %>
    <div class="right">
      <a href = "/trainings/new" class = "ui right labeled icon red compact button" id = "red_button">
        <i class="write square icon"></i>
        Create New Training
      </a>
    </div>
    <% end %>
  </div>
  <div class="clear"></div>

  <%= render :file=> 'app/views/partials/message.html.erb' %>

  <div class="ui segment">
    <% if current_user.is_admin %>
    <table id="forms" class="ui red selectable celled striped table">
      <thead class = "center aligned">
        <th>Training Title</th>
        <th>Description</th>
        <th>Status</th>
        <th>Associated Skill</th>
        <th>Associated Form</th>
      </thead>
      <tbody>
        <% @trainings.each do |training| %>
        <tr>
          <td class = "three wide center aligned">
            <%= link_to training_path(training) do %>
              <h4> <%= training.title %> </h4>
            <% end %>
          </td>
          <td><%= training.description %></td>
          <td class = "center aligned"><%=training.status %></td>


          <% @questions.each do |ques| %>
            <% if (training.question_id == ques.id) %>
              <td class = "two wide"> <%= ques.questionDescription %> </td>
            <% end %>
          <% end %>

          <% @forms.each do |f| %>
            <% if (training.form_id == f.id) %>
              <td class = "two wide"> <%= f.title %> </td>
            <% end %>
          <% end %>

        </tr>
        <% end %>
      </tbody>
      </table>
      <% else %>
      <% if @invited.size == 0 and @going.size == 0 %>
        <h4 class = "ui centered aligned header">Nothing to display.</h4>
      <% else %>
      <table id="recommended" class="ui red selectable celled table">
        <thead class = "center aligned">
          <th>Training</th>
          <th>Description</th>
          <th>Status</th>

        </thead>
        <tbody>
            <% @invited.each do |r| %>
            <tr>
            <td class = "four wide"><%= r.training.title %></td>
            <td class = "eight wide"><%= r.training.description %></td>
            <td>
              <%= button_to "Going", {action: "accept", id: r.id}, method: :POST, class: "ui left floated compact red button", id: "red_button", style:"margin-left:19px" %>
              <%= button_to "Not Going", {action: "deny", id: r.id}, method: :POST, class: "ui floated compact black button", style: "margin-left: 25px" %>
            </td>
            </tr>
            <% end %>

            <% @going.each do |r| %>
            <tr>
            <td class = "four wide"><%= r.training.title %></td>
            <td class = "eight wide"><%= r.training.description %></td>
            <td class = "ui center aligned">
              <button class = "ui compact active green button", style = "background-color:#206b33">Going</button>
            </td>
            </tr>
            <% end %>
        </tbody>
      </table>
      <% end %>
      <% end %>
  </div>
  <br><br>
</div>

app/views/trainings/new.html.erb
<%= render :file=> 'app/views/partials/sidebar.html.erb' %>

<div class = "pusher">
  <div class="ui basic segment">
    <div class="left">
      <h1 class="ui header"><i class="red add circle icon"></i>New Training</h1>
    </div>

  	</div>
  	<div class="clear"></div>

<%= render 'form', training: @training %>

app/views/trainings/show.html.erb
<%= render :file=> 'app/views/partials/sidebar.html.erb' %>
  <div class = "pusher">

      <div class="ui basic segment">
    <div class="left">
      <h1 class="ui header">
        <a href = "/trainings"><i class="red arrow circle left icon"></i></a>
        <%= @training.title %></h1>
    </div>
    <div class="right">
      <%= link_to 'Edit', edit_training_path(@training), :class=>"ui red button", :id=>"red_button" %>
      <%= link_to 'Delete', training_path(@training), :class=>"ui black button",
              method: :delete,
              data: {confirm: 'Are you sure?'} %>
    </div> <br>

    </div>

    <div class="clear"></div>

    <%= render :file=> 'app/views/partials/message.html.erb' %>

    <div class = "ui top attached tabular menu">
      <a class = "active red item" data-tab="first">
        <h4><i class="red info circle icon"></i>Training Information</h4>
      </a>
      <a class = "red item" data-tab="second">
        <h4>Recommended List</h4>
      </a>
    </div>

    <div class = "ui attached active tab segment" data-tab = "first">
      <div class="ui large divided selection list">
        <div class="item">
          <div class="header">Description</div>
          <%= @training.description %>
        </div>
        <div class="item">
          <div class="header">Status</div>
          <%= @training.status %>
        </div>
        <div class="item">
          <div class="header">Venue</div>
          <%= @training.venue %>
        </div>
        <div class="item">
          <div class="header">Deadline</div>
          <%= if @training.date != nil
            @training.date.strftime("%b %d, %Y")
            end %>
        </div>
        <div class="item">
          <div class = "header"> Associated Skill </div>
            <% @questions.each do |ques| %>
                <% if (@training.question_id == ques.id) %>
                  <div class="item"> <%= ques.questionDescription %> </div>
                <% end %>
            <% end %>
        </div>
        <div class = "item">
          <div class = "header">Associated Form</div>
            <% @forms.each do |f| %>
              <% if (@training.form_id == f.id) %>
                <div class="item"> <%= f.title %> </div>
              <% end %>
            <% end %>
        </div>
      </div> <!-- list -->

      <div class = "ui segment">
      <table id = "invited" class = "red ui selectable celled striped table">
        <thead class ="center aligned">
          <th>List of Invited Employees</th>
          <th>Status</th>
        </thead>

        <tbody>
          <% @invites.each do |r| %>
          <tr>
          <td><%= r.user.full_name %></td>
          <td><%= r.recommendation %></td>
          </tr>
          <% end %>
        </tbody>

      </table>

      </div>

    </div>

    <div class="ui attached tab segment" data-tab="second">
      <table id="recommended" class="ui red selectable celled table">
        <thead class = "center aligned">
          <th>Recommended Employee</th>
          <th>Essay Answer</th>
          <th>Invite</th>

        </thead>
        <tbody>
            <% @recom.each do |r| %>
            <tr>
            <td><%= r.user.full_name %></td>
            <td>Insert essay here</td>
            <td class = "three wide">
              <%= button_to "Invite", {action: "invite", id: r.id}, method: :POST, class: "ui left floated compact red button", id: "red_button" %>
              <%= button_to "Reject", {action: "reject", id: r.id}, method: :POST, class: "ui right floated compact black button" %>
            </td>
            </tr>
            <% end %>
        </tbody>
      </table>

    </div>
<br>
</div>