config/routes.rb
Rails.application.routes.draw do

  resources :trainings
  get 'users/show'

  get 'users/index'

  get 'home/show'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'welcome/index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'forms_questions/submit', to: 'forms_questions#submit'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :answers
  resources :forms_questions
  resources :forms
  resources :questions
  resources :recommendations
  resources :recommended_list
  # resources :users, only: [:show, :index]
  get 'profile', to: 'profiles#index'
  get 'profile/edit', to: 'profiles#edit'
  patch 'profile/update', to: 'profiles#update'
  post 'tranings/invite/', to: 'trainings#invite'
  post 'tranings/reject/', to: 'trainings#reject'
  post 'tranings/accept/', to: 'trainings#accept'
  post 'tranings/deny/', to: 'trainings#deny'
  post 'users/set_admin/', to: 'users#set_admin'
  post 'users/unset_admin/', to: 'users#unset_admin'
  get 'users/:user_id' => 'users#show', as: :usersshow
  root to: "home#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :forms_questions, :dependent => :destroy
    has_many :forms, through: :forms_questions
    has_many :trainings
    validates :questionDescription, presence: true
    validates :skill, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authorize_admin
  def index
    @questions = Question.all
  end
  def show
    @question = Question.find(params[:id])
  end
  def new
    @question = Question.new
  end
  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(question_params)
    if @question.valid?
      @question.save
      flash[:success_header] = @question.questionDescription + " has been created!"
      flash[:success_body] = "The question has been saved to the database."
      redirect_to questions_path
    else
      render 'new'
    end
  end
  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      flash[:success_header] = @question.questionDescription + " has been updated!"
      flash[:success_body] = "The changes have been saved to the database."
      redirect_to @question
    else
      render 'edit'
    end
  end
  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    flash[:success_header] = @question.questionDescription + " has been deleted!"
    flash[:success_body] = "The changes have been saved to the database."
    redirect_to questions_path
  end
  private
    def question_params
      params.require(:question).permit(:questionDescription, :area, :skill)
    end

    def authorize_admin
      if !current_user.is_admin?
        flash[:error_header] = "Sorry, you are not authorized to view this page."
        flash[:error_body] = "You have been redirected to your profile."
        redirect_to '/profile'
      end
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.erb
<div class="ui segments">
    <div class="ui horizontal segments">
      <div class="ui segment">
        <h3 class="ui dividing header"><i class="red info circle icon"></i>Question Information</h3>

    <%= form_for @question do |f| %>

    <div class="ui form">
    <div class="ui two column grid">
    <div class="column">
    <div class="field">
    <label>Question</label>
    <%= f.text_field :questionDescription, placeholder: "Question" %>
    <% if @question.errors[:questionDescription].any? %>
    <div class="ui basic red pointing prompt label transition visible">
    <%= "Question " << @question.errors[:questionDescription].join(", ") %>
    </div>
    <% end %>
    <br>
    </div>

    </div>
    <div class="column">

    <div class="field">
    <label>Skill</label>
    <%= f.text_field :skill, placeholder: "Skill" %>
    <% if @question.errors[:skill].any? %>
    <div class="ui basic red pointing prompt label transition visible">
    <%= "Skill " << @question.errors[:skill].join(", ") %>
    </div>
    <% end %><br>
    </div>

    </div>
    </div>

    </div>
    </div> <!-- end info segment -->
  </div>
  <div class="ui center aligned segment">
  <div class="eight wide centered column">
  Please review all fields before submitting.
  <br><br>
  <button type="submit" name="submit-button" class="ui red button submit-button" id="red_button">
    Save
  </button>
  <%= link_to 'Cancel', questions_path, class:"ui black button"%>
  </div>
  <% end %>
  </div>
  </div>

  <br><br><br><br>

app/views/questions/edit.html.erb
<%= render :file=> 'app/views/partials/sidebar.html.erb' %>

<div class = "pusher">
  <div class="ui basic segment">
    <div class="left">
      <h1 class="ui header"><i class="red edit icon"></i>Edit: <%= @question.questionDescription %></h1>
    </div>
  </div>
  <div class="clear"></div>
    <%= render 'question', question: @question %>
  </div>

app/views/questions/index.html.erb
<%= render :file=> 'app/views/partials/sidebar.html.erb' %>

<% if current_user.is_admin%>

<div class = "pusher">
  <div class="ui basic segment">
    <div class="left">
      <h1 class="ui header"><i class="red align justify icon"></i>Questions</h1>
    </div>
    <div class="right">
        <a href = "/questions/new" class = "ui right labeled icon red compact button" id = "red_button">
          <i class="write square icon"></i>
          Add Question
        </a>
    </div>
  </div>
  <div class="clear"></div>

  <%= render :file=> 'app/views/partials/message.html.erb' %>

  <div class="ui segment">
    <table id="questions" class="ui red selectable celled striped table">
    		<thead>
    			<tr class = "center aligned">
              <th class = "three wide">Skill</th>
        			<th>Question</th>
      		</tr>
    		</thead>
    		<tbody>
     			<% @questions.each do |question| %>
  	    		<tr>
                <td> <%= question.skill %> </td>
  	      			<td>
                  <%= link_to question_path(question) do %>
                    <h4><%= question.questionDescription %> </h4>
                  <% end %>

                </td>
  	   			</tr>
  	  		<% end %>
    		</tbody>
  	</table>
  </div>
  <br><br>
</div>
<% end %>

app/views/questions/new.html.erb
<%= render :file=> 'app/views/partials/sidebar.html.erb' %>

<div class = "pusher">
  <div class="ui basic segment">
    <div class="left">
      <h1 class="ui header"><i class="red add circle icon"></i>New Question</h1>
    </div>
  	</div>
  	<div class="clear"></div>
	<%= render 'question', question: @question %>
</div>

app/views/questions/show.html.erb
<%= render :file=> 'app/views/partials/sidebar.html.erb' %>
  <div class = "pusher">
      <div class="ui basic segment">
    <div class="left">
      <h1 class="ui header">
        <a href = "/questions"><i class="red arrow circle left icon"></i></a>
        <%= @question.questionDescription %></h1>
    </div>
    <div class="right">
      <%= link_to 'Edit', edit_question_path(@question), :class=>"ui red button", :id=>"red_button" %>
      <%= link_to 'Delete', question_path(@question), :class=>"ui black button",
              method: :delete,
              data: {confirm: 'Are you sure?'} %>
    </div>
    </div>
    <div class="clear"></div>

    <%= render :file=> 'app/views/partials/message.html.erb' %>

    <div class="ui segments">
      <div class="ui segment">
      <h3 class="ui dividing header"><i class="red info circle icon"></i>Question Information</h3>
      <div class="ui large divided selection list">
        <div class="item">
          <div class="header">Description</div>
          <%= @question.questionDescription %>
        </div>
        <div class="item">
          <div class="header">Skill</div>
          <%= @question.skill %>
        </div>
      </div> <!-- list -->
      </div>

      </div>
    <br><br><br>
</div>