config/routes.rb
Rails.application.routes.draw do

  resources :trainings
  get 'users/show'

  get 'users/index'

  get 'home/show'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'welcome/index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'forms_questions/submit', to: 'forms_questions#submit'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :answers
  resources :forms_questions
  resources :forms
  resources :questions
  resources :recommendations
  resources :recommended_list
  # resources :users, only: [:show, :index]
  get 'profile', to: 'profiles#index'
  get 'profile/edit', to: 'profiles#edit'
  patch 'profile/update', to: 'profiles#update'
  post 'tranings/invite/', to: 'trainings#invite'
  post 'tranings/reject/', to: 'trainings#reject'
  post 'tranings/accept/', to: 'trainings#accept'
  post 'tranings/deny/', to: 'trainings#deny'
  post 'users/set_admin/', to: 'users#set_admin'
  post 'users/unset_admin/', to: 'users#unset_admin'
  get 'users/:user_id' => 'users#show', as: :usersshow
  root to: "home#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :forms_question
  belongs_to :user #, :foreign_key => 'uid'
  
  # validates :uid, :presence => true
end

app/models/form.rb
class Form < ApplicationRecord
  has_many :forms_questions, :dependent => :destroy
  has_many :questions, through: :forms_questions
  has_one :training
  validates :title, presence: true
  validates :deadline, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @answers = Answer.all
    @users = User.all
    @forms = Form.all
    @forms_questions = FormsQuestion.all
    @questions = Question.all
  end
  def show
    @users = User.all
    @form = Form.find(params[:id])
    @question = Question.find(params[:ques])
    @rows = FormsQuestion.where(form_id: params[:id], question_id: params[:ques])
    @answer = Answer.where(forms_question_id: @rows)
  end
  def new
    @answer = Answer.new
  end

  def create
    @answer = Answer.new
    user = User.find(current_user.id);
    Answer.where(user_id: current_user.id, forms_question_id: params[:fq_id]).first_or_initialize.tap do |a|
      a.comp_level = params[:comp_level]
      a.imp_level = params[:imp_level]
      if a.save!(validate: false)
        respond_to do |format|
          format.json { render :json =>a}
        end
        # TrainingLog.recommend_(user)
      end
    end
  end

  def update
    # user = User.find(current_user.id);
    # if @answer.update(params)
      # TrainingLog.recommend_(user)
    # end
  end

  private
    def answer_params
      params.permit(:comp_level, :imp_level)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/index.html.erb
<%= render :file=> 'app/views/partials/sidebar.html.erb' %>

<div class = "pusher">
    <div class="ui basic segment">
        <div class="left">
            <h1 class="ui header"><i class="red check circle icon"></i>Answers Summary</h1>
        </div>
    </div>
    <div class="clear"></div>
    <div class="ui header accordion">
        <% @forms.each do |f| %>
            <% if f.question_ids.size > 0 %>
                <div id="form" class="ui center aligned segment title">
                    <%= f.title %>
                </div>
                <div id="question" class="ui header content">
                    <div class="accordion">
                        <% f.question_ids.each_with_index do |q, index| %>
                            <% @questions.each do |ques| %>
                                <% if (q == ques.id) %>
                                    <div id="q_title" class="ui header title">
                                        <i class="dropdown icon"></i>
                                        <%= ques.questionDescription %>
                                        <!-- <div class="ui divider"></div> -->
                                    </div>
                                    <div id="table" class="ui header content">
                                        <% @rows = @forms_questions.where(form_id: f.id, question_id: q) %>
                                        <% @answer = @answers.where(forms_question_id: @rows) %>
                                        <% @criteria = @answer.where(comp_level: 1, imp_level: 4) %>
                                        <% if @answer.size == 0 %>
                                            <div style="text-align: center">No users to display.</div>
                                        <% else %>
                                          <span>  <%= @criteria.size %> out of <%=@answer.size %> (<%= number_to_percentage(@criteria.size.to_f / @answer.size.to_f * 100.0, precision: 0) %>) employees answered with Competence: 1 and Importance: 4 </span>
                                            <table class="ui celled table">
                                                <thead>
                                                    <tr>
                                                        <th class="ten wide">User</th>
                                                        <th>Competence Level</th>
                                                        <th>Importance Level</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <% @answer.limit(10).each do |a| %>
                                                        <tr>
                                                            <% @user = @users.find(a.user_id) %>
                                                            <td><%= @user.full_name %></td>
                                                            <td><%= a.comp_level %></td>
                                                            <td><%= a.imp_level %></td>
                                                        </tr>
                                                    <% end %>
                                                </tbody>
                                            </table>
                                            <% if @answer.size > 0 %>
                                                <%= link_to 'See all', answer_path(f.id, :ques=>q), :class => "right aligned small header", :style => "margin-right: 10px"%>
                                                <div class="clear"></div>
                                            <% end %>
                                        <% end %>
                                    </div>
                                <% end %>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/answers/show.html.erb
<%= render :file=> 'app/views/partials/sidebar.html.erb' %>

<div class = "pusher">
    <div class="ui basic segment">
        <div class="left">
            <h1 class="ui header"><i class="red check circle icon"></i>Answers Summary</h1>
        </div>
    </div>
    <div class="clear"></div>
        <div class="ui segment">
            <h1 class="ui right floated header" style="text-align:right">
                <%= @form.title %>
                <div class="sub header"><%= @question.questionDescription %></div>
            </h1>
            <div class="ui clearing divider"></div>
            <table id="forms" class="ui selectable celled striped table">
                <thead>
                    <tr>
                        <th class="ten wide">User</th>
                        <th>Competence Level</th>
                        <th>Importance Level</th>
                    </tr>
                </thead>
                <tbody>
                    <% @answer.each do |a| %>
                        <tr>
                            <% @user = @users.find(a.user_id) %>
                            <td><%= @user.full_name %></td>
                            <td><%= a.comp_level %></td>
                            <td><%= a.imp_level %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
    <br><br><br>
</div>