config/routes.rb
Rails.application.routes.draw do

  resources :trainings
  get 'users/show'

  get 'users/index'

  get 'home/show'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'welcome/index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'forms_questions/submit', to: 'forms_questions#submit'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :answers
  resources :forms_questions
  resources :forms
  resources :questions
  resources :recommendations
  resources :recommended_list
  # resources :users, only: [:show, :index]
  get 'profile', to: 'profiles#index'
  get 'profile/edit', to: 'profiles#edit'
  patch 'profile/update', to: 'profiles#update'
  post 'tranings/invite/', to: 'trainings#invite'
  post 'tranings/reject/', to: 'trainings#reject'
  post 'tranings/accept/', to: 'trainings#accept'
  post 'tranings/deny/', to: 'trainings#deny'
  post 'users/set_admin/', to: 'users#set_admin'
  post 'users/unset_admin/', to: 'users#unset_admin'
  get 'users/:user_id' => 'users#show', as: :usersshow
  root to: "home#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/form.rb
class Form < ApplicationRecord
  has_many :forms_questions, :dependent => :destroy
  has_many :questions, through: :forms_questions
  has_one :training
  validates :title, presence: true
  validates :deadline, presence: true
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :authorize_admin
  def index
    @forms = Form.all
  end
  def show
    @form = Form.find(params[:id])
    @questions = Question.all
  end
  def new
    # if (!current_user.is_admin)
    #   redirect_to forms_path
    # end
    @form = Form.new
  end
  def edit
    @form = Form.find(params[:id])
  end

  def create
    # if (!current_user.is_admin)
    #   redirect_to forms_path
    # end
    @form = Form.new(form_params)
    if @form.valid?
      @form.save
      flash[:success_header] = @form.title + " has been created!"
      flash[:success_body] = "The form has been saved to the database."
      redirect_to forms_path
    else
      render 'new'
    end
  end
  
  def update
    @form = Form.find(params[:id])
    if @form.update(form_params)
      flash[:success_header] = @form.title + " has been updated!"
      flash[:success_body] = "The changes have been saved to the database."
      redirect_to @form
    else
      render 'edit'
    end
  end

  def destroy
    # if (!current_user.is_admin)
    #   redirect_to forms_path
    # end
    @form = Form.find(params[:id])
    @form.destroy
    flash[:success_header] = @form.title + " has been deleted!"
    flash[:success_body] = "The changes have been saved to the database."
    redirect_to forms_path
  end
  private
    def form_params
      params.require(:form).permit(:title, :description, :deadline, :question_ids => [])
    end

    def authorize_admin
      if !current_user.is_admin?
        flash[:error_header] = "Sorry, you are not authorized to view this page."
        flash[:error_body] = "You have been redirected to your profile."
        redirect_to '/profile'
      end
    end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<div class="ui segments">
    <div class="ui horizontal segments">
      <div class="ui segment">
    <h3 class="ui dividing header"><i class="red info circle icon"></i>Form Information</h3>

    <%= form_for @form do |f| %>

    <div class="ui form">
    <div class="field">
    <label>Form Title</label>
    <%= f.text_field :title, placeholder: "Form Title" %>
    <% if @form.errors[:title].any? %>
    <div class="ui basic red pointing prompt label transition visible">
    <%= "Title " << @form.errors[:title].join(", ") %>
    </div>
    <% end %>
    <br>
    </div>
    <div class="field">
    <label>Description</label>
    <%= f.text_field :description, placeholder: "Form Description" %><br>
    </div>
    <div class="ui calendar" id="date"><div class="field">
    <label>Deadline</label>
    <%= f.date_field :deadline, placeholder: "yyyy-mm-dd" %>
    <% if @form.errors[:deadline].any? %>
    <div class="ui basic red pointing prompt label transition visible">
    <%= "Deadline " << @form.errors[:deadline].join(", ") %>
    </div>
    <% end %>
    <br>
    </div></div>
    </div>
    </div> <!-- end info segment -->

    <div class="ui segment" style="width: 30%">
    <h3 class="ui dividing header"><i class="red  help circle icon"></i>Questions to Include</h3>
    <input type="checkbox" id="selectAll" class="ui checkbox"/> Check / Uncheck All Questions

    <% Question.all.group_by(&:skill).each do |skill, questions| %>
      <h4> <%= skill %></h4>
      <% questions.each do |question| %><p>
        <%= check_box_tag "form[question_ids][]", question.id, f.object.questions.include?(question), class: "ui checkbox check" %>
        <%= question.questionDescription %></p>
      <% end %>
      <div class="ui divider"></div>
    <% end %>
      </div> <!-- end questions segment -->
  </div>
  <div class="ui center aligned segment">
  <div class="eight wide centered column">
  Please review all fields before submitting.
  <br><br>
  <button type="submit" name="submit-button" class="ui red button submit-button" id = "red_button">
    Save
  </button>
  <%= link_to 'Cancel', forms_path, class:"ui black button"%>
  </div>
  <% end %>
  </div>
  </div>
  <br><br><br><br>

app/views/forms/edit.html.erb
<%= render :file=> 'app/views/partials/sidebar.html.erb' %>

<div class = "pusher">
  <div class="ui basic segment">
    <div class="left">
      <h1 class="ui header"><i class="red edit icon"></i>Edit Form: <%= @form.title %></h1>
    </div>
  </div>
  <div class="clear"></div>
    <%= render 'form', form: @form %>
</div>

app/views/forms/index.html.erb
<%= render :file=> 'app/views/partials/sidebar.html.erb' %>

<div class = "pusher">
  <div class="ui basic segment">
    <div class="left">
      <h1 class="ui header"><i class="red block layout icon"></i>Forms</h1>
    </div>
    <div class="right">
      <a href = "/forms/new" class = "ui right labeled icon red compact button" id = "red_button">
        <i class="write square icon"></i>
        Create New Form
      </a>
    </div>
  </div>
  <div class="clear"></div>

  <%= render :file=> 'app/views/partials/message.html.erb' %>

  <div class="ui segment">
    <table id="forms" class="ui red selectable celled striped table">
      <thead class = "center aligned">
        <th>Form Title</th>
        <th>Description</th>
        <th>Status</th>
        <th>Date Added</th>
        <th>Deadline</th>
      </thead>
      <tbody>
        <% @forms.each do |form| %>
        <tr>
          <td class = "center aligned">
            <%= link_to form_path(form), id: form.title do %>
              <h4><%= form.title %></h4>
            <% end %>
          </td>
          <td><%= form.description %></td>
          <td><%=form.status %></td>
          <td><%= form.created_at.strftime("%b %d, %Y") %></td>
          <td><%=form.deadline.strftime("%b %d, %Y") %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <br><br>
</div>

app/views/forms/new.html.erb
<%= render :file=> 'app/views/partials/sidebar.html.erb' %>

<div class = "pusher">
  <div class="ui basic segment">
    <div class="left">
      <h1 class="ui header"><i class="red add circle icon"></i>New Form</h1>
    </div>

  </div>
  <div class="clear"></div>

  <%= render 'form', form: @form %>
</div>

app/views/forms/show.html.erb
<%= render :file=> 'app/views/partials/sidebar.html.erb' %>

<div class = "pusher">
  <div class="ui basic segment">
    <div class="left">
      <h1 class="ui header">
        <a href = "/forms"><i class="red arrow circle left icon"></i></a>
        <%= @form.title %></h1>
    </div>
    <div class="right">
      <%= link_to 'Edit', edit_form_path(@form), :class=>"ui red button", :id=>"edit"%>
      <%= link_to 'Delete', form_path(@form), :id=>"delete", :class=>"ui black button",
              method: :delete,
              data: {confirm: 'Are you sure?'} %>
    </div>
    </div>
    <div class="clear"></div>

    <%= render :file=> 'app/views/partials/message.html.erb' %>

    <div class="ui segments">
      <div class="ui horizontal segments">
      <div class="ui segment">
      <h3 class="ui dividing header"><i class="red info circle icon"></i>Form Information</h3>
      <div class="ui large divided selection list">
        <div class="item">
          <div class="header">Description</div>
          <%= @form.description %>
        </div>
        <div class="item">
          <div class="header">Status</div>
          <%= @form.status %>
        </div>
        <div class="item">
          <div class="header">Deadline</div>
          <%= @form.deadline.strftime("%b %d, %Y") %>
        </div>
      </div> <!-- list -->
      </div>

      <div class="ui segment" style="width: 40%;">
      <h3 class="ui dividing header"><i class="red help circle icon"></i>Questions Included</h3>
      <% @form.questions.group_by(&:skill).each do |skill, questions| %>
        <h4><%= skill %></h4>
        <div class="ui large list">
        <% questions.each do |question| %>
          <div class="item"><i class="red selected radio icon"></i><div class="content"><%= question.questionDescription %></div>
          </div>
        <% end %>
        </div>
      <% end %>
      </div>

      </div>
      </div>
    <br><br><br>
</div>